# Derived from KellerJordan/modded-nanogpt ecbb586296d3dac36fd206211f25d63bad4a6b35.
# MIT license: modded_medium_LICENSE. Generated by build_modded_medium.py.
# Exact upstream and patch manifest are retained durably; do not hand-edit.
import os
import sys

import copy
import glob
import math
import threading
import time
import uuid
from dataclasses import dataclass
from collections import Counter, defaultdict
from itertools import accumulate
from pathlib import Path
import gc

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"
import torch

import torch._dynamo as dynamo
import torch.utils.checkpoint
import torch.distributed as dist
import torch.nn.functional as F

# torch._inductor.config.coordinate_descent_tuning = True # we have banned this flag for new records because it causes compilation to take 30min
import triton
import triton.language as tl
from torch import Tensor, nn

from modded_arch import swiglu_hidden
from modded_diffattn import diff_attention
from modded_moe import MoE

dynamo.config.recompile_limit = 64


# -----------------------------------------------------------------------------
# Custom operators: FP8 matmul by @YouJiacheng


@torch.library.custom_op("nanogpt::mm", mutates_args=())
def mm_op(
    x: Tensor, w: Tensor, x_s: float, w_s: float, grad_s: float
) -> tuple[Tensor, Tensor, Tensor]:
    @torch.compile
    def impl(x: Tensor, w: Tensor):
        assert x.is_contiguous() and w.is_contiguous()
        x_f8 = x.div(x_s).to(torch.float8_e4m3fn)
        w_f8 = w.div(w_s).to(torch.float8_e4m3fn)
        out = torch._scaled_mm(
            x_f8,
            w_f8.T,
            out_dtype=torch.bfloat16,
            scale_a=x.new_tensor(x_s, dtype=torch.float32),
            scale_b=x.new_tensor(w_s, dtype=torch.float32),
            use_fast_accum=True,
        )
        return out, x_f8, w_f8

    return impl(x, w)


@mm_op.register_fake
def _(x: Tensor, w: Tensor, *_):
    assert x.ndim == w.ndim == 2
    assert x.shape[1] == w.shape[1]
    assert x.device == w.device
    assert x.is_contiguous() and w.is_contiguous()
    return x @ w.T, x.to(torch.float8_e4m3fn), w.to(torch.float8_e4m3fn)


@torch.library.custom_op("nanogpt::mm_backward", mutates_args=())
def mm_backward_op(
    g: Tensor, x_f8: Tensor, w_f8: Tensor, x_s: float, w_s: float, grad_s: float
) -> tuple[Tensor, Tensor]:
    @torch.compile
    def impl(grad: Tensor, x_f8: Tensor, w_f8: Tensor):
        assert grad.is_contiguous()
        x_inv_s = grad.new_tensor(x_s, dtype=torch.float32)
        w_inv_s = grad.new_tensor(w_s, dtype=torch.float32)
        grad_inv_s = grad.new_tensor(grad_s, dtype=torch.float32)
        grad_f8 = grad.div(grad_s).to(torch.float8_e5m2)
        grad_x = torch._scaled_mm(
            grad_f8,
            w_f8.T.contiguous().T,
            out_dtype=torch.bfloat16,
            scale_a=grad_inv_s,
            scale_b=w_inv_s,
            use_fast_accum=False,
        )
        # faster than grad_f8_t @ x_f8, for (d_out, d_in) == (50304, 768)
        grad_w = torch._scaled_mm(
            x_f8.T.contiguous(),
            grad_f8.T.contiguous().T,
            out_dtype=torch.float32,
            scale_a=x_inv_s,
            scale_b=grad_inv_s,
            use_fast_accum=False,
        ).T
        return grad_x, grad_w

    return impl(g, x_f8, w_f8)


@mm_backward_op.register_fake
def _(g: Tensor, x_f8: Tensor, w_f8: Tensor, *_):
    return x_f8.to(torch.bfloat16), w_f8.T.contiguous().T.to(torch.float32)


def backward(ctx, grad_out: Tensor, *_):
    x_f8, w_f8 = ctx.saved_tensors
    x_s, w_s, grad_s = ctx.scales
    grad_x, grad_w = torch.ops.nanogpt.mm_backward(
        grad_out, x_f8, w_f8, x_s, w_s, grad_s
    )
    return grad_x, grad_w, None, None, None


def setup_context(ctx: torch.autograd.function.FunctionCtx, inputs, output):
    *_, x_s, w_s, grad_s = inputs
    _, x_f8, w_f8 = output
    ctx.save_for_backward(x_f8, w_f8)
    ctx.scales = x_s, w_s, grad_s
    ctx.set_materialize_grads(False)


mm_op.register_autograd(backward, setup_context=setup_context)

# -----------------------------------------------------------------------------
# Triton kernel for symmetric matrix multiplication by @byronxu99


def _get_autotune_configs():
    return [
        triton.Config(
            {
                "BLOCK_SIZE_M": bm,
                "BLOCK_SIZE_N": bn,
                "BLOCK_SIZE_K": bk,
                "GROUP_SIZE_M": 8,
                "LOWER_UPPER": 1,
            },
            num_stages=stages,
            num_warps=warps,
        )
        for bm in [64, 128]
        for bn in [64, 128, 256]
        for bk in [64, 128]
        for stages, warps in [(3, 4), (3, 8), (4, 4)]
        if bm // bn <= 2 and bn // bm <= 2
    ]


@triton.jit
def _pid_to_block(
    pid,
    M,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
):
    # Split output matrix into blocks of size (BLOCK_SIZE_M, BLOCK_SIZE_N)
    num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(M, BLOCK_SIZE_N)

    # Map PID to a single matrix in batch
    batch_idx = pid // (num_pid_m * num_pid_n)
    pid = pid % (num_pid_m * num_pid_n)

    # Map PID to 2D grid of blocks
    pid_m = pid // num_pid_n
    pid_n = pid % num_pid_n
    pid_m, pid_n = tl.swizzle2d(pid_m, pid_n, num_pid_m, num_pid_n, GROUP_SIZE_M)

    m_idx = pid_m * BLOCK_SIZE_M
    n_idx = pid_n * BLOCK_SIZE_N
    return batch_idx, m_idx, n_idx


@triton.autotune(
    configs=_get_autotune_configs(),
    key=["M", "K", "a_stride_r", "a_stride_c", "c_stride_r", "c_stride_c"],
)
@triton.jit
def XXT_kernel(
    A_ptr,
    C_ptr,
    M,
    K,
    a_stride_b,
    a_stride_r,
    a_stride_c,
    c_stride_b,
    c_stride_r,
    c_stride_c,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    LOWER_UPPER: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    batch_idx, m_idx, n_idx = _pid_to_block(
        pid, M, BLOCK_SIZE_M, BLOCK_SIZE_N, GROUP_SIZE_M
    )

    # Skip blocks that don't need to be computed
    skip_block_below_diag = (LOWER_UPPER == 0) and (n_idx + BLOCK_SIZE_N <= m_idx)
    skip_block_above_diag = (LOWER_UPPER != 0) and (m_idx + BLOCK_SIZE_M <= n_idx)
    if skip_block_below_diag or skip_block_above_diag:
        return

    # Index into one matrix of batch
    A_ptr += batch_idx * a_stride_b
    C_ptr += batch_idx * c_stride_b

    # Create pointer arrays for A and A.T
    offs_m = (m_idx + tl.arange(0, BLOCK_SIZE_M)) % M
    offs_n = (n_idx + tl.arange(0, BLOCK_SIZE_N)) % M
    offs_k = tl.arange(0, BLOCK_SIZE_K)
    a_ptrs = A_ptr + (offs_m[:, None] * a_stride_r + offs_k[None, :] * a_stride_c)
    at_ptrs = A_ptr + (offs_k[:, None] * a_stride_c + offs_n[None, :] * a_stride_r)

    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    # Accumulate over blocks of K
    for k in tl.range(0, tl.cdiv(K, BLOCK_SIZE_K)):
        a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * BLOCK_SIZE_K, other=0.0)
        at = tl.load(at_ptrs, mask=offs_k[:, None] < K - k * BLOCK_SIZE_K, other=0.0)
        accumulator = tl.dot(a, at, accumulator)
        a_ptrs += BLOCK_SIZE_K * a_stride_c
        at_ptrs += BLOCK_SIZE_K * a_stride_c

    out_dtype = C_ptr.dtype.element_ty
    output = accumulator.to(out_dtype)

    # Store block of C
    offs_cm = m_idx + tl.arange(0, BLOCK_SIZE_M)
    offs_cn = n_idx + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = C_ptr + (offs_cm[:, None] * c_stride_r + offs_cn[None, :] * c_stride_c)
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < M)
    tl.store(c_ptrs, output, mask=c_mask)

    # Store block of C mirrored across the diagonal
    c_ptrs_t = C_ptr + (offs_cn[:, None] * c_stride_r + offs_cm[None, :] * c_stride_c)
    c_mask_t = (offs_cn[:, None] < M) & (offs_cm[None, :] < M)
    tl.store(c_ptrs_t, output.T, mask=c_mask_t)


def XXT(A: torch.Tensor, out: torch.Tensor):
    """
    Launch Triton kernel to compute C = A @ A.T
    """
    assert A.ndim == 2 or A.ndim == 3
    M, K = A.shape[-2:]
    assert out.size(-2) == M, "Output matrix has incorrect shape"
    assert out.size(-1) == M, "Output matrix has incorrect shape"

    batch_size = A.size(0) if A.ndim == 3 else 1
    input_batch_stride = A.stride(0) if A.ndim == 3 else 0
    output_batch_stride = out.stride(0) if out.ndim == 3 else 0

    grid = lambda meta: (
        batch_size
        * triton.cdiv(M, meta["BLOCK_SIZE_M"])
        * triton.cdiv(M, meta["BLOCK_SIZE_N"]),
    )
    XXT_kernel[grid](
        A_ptr=A,
        C_ptr=out,
        M=M,
        K=K,
        a_stride_b=input_batch_stride,
        a_stride_r=A.stride(-2),
        a_stride_c=A.stride(-1),
        c_stride_b=output_batch_stride,
        c_stride_r=out.stride(-2),
        c_stride_c=out.stride(-1),
    )
    return out


@triton.autotune(
    configs=_get_autotune_configs(),
    key=["M", "a_stride_r", "a_stride_c", "c_stride_r", "c_stride_c"],
)
@triton.jit
def ba_plus_cAA_kernel(
    A_ptr,
    C_ptr,
    M,
    a_stride_b,
    a_stride_r,
    a_stride_c,
    c_stride_b,
    c_stride_r,
    c_stride_c,
    alpha,
    beta,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    LOWER_UPPER: tl.constexpr,
):
    # This is mostly duplicated from XXT_kernel, but also loads and adds a block of A
    # Performance is slightly slower than XXT_kernel, so we use two separate kernels
    pid = tl.program_id(axis=0)
    batch_idx, m_idx, n_idx = _pid_to_block(
        pid, M, BLOCK_SIZE_M, BLOCK_SIZE_N, GROUP_SIZE_M
    )

    # Skip blocks that don't need to be computed
    skip_block_below_diag = (LOWER_UPPER == 0) and (n_idx + BLOCK_SIZE_N <= m_idx)
    skip_block_above_diag = (LOWER_UPPER != 0) and (m_idx + BLOCK_SIZE_M <= n_idx)
    if skip_block_below_diag or skip_block_above_diag:
        return

    # Index into one matrix of batch
    A_ptr += batch_idx * a_stride_b
    C_ptr += batch_idx * c_stride_b

    # Create pointer arrays for A and A.T
    offs_m = (m_idx + tl.arange(0, BLOCK_SIZE_M)) % M
    offs_n = (n_idx + tl.arange(0, BLOCK_SIZE_N)) % M
    offs_k = tl.arange(0, BLOCK_SIZE_K)
    a_ptrs = A_ptr + (offs_m[:, None] * a_stride_r + offs_k[None, :] * a_stride_c)
    at_ptrs = A_ptr + (offs_k[:, None] * a_stride_c + offs_n[None, :] * a_stride_r)

    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)

    # Accumulate over blocks of K
    for k in tl.range(0, tl.cdiv(M, BLOCK_SIZE_K)):
        a = tl.load(a_ptrs, mask=offs_k[None, :] < M - k * BLOCK_SIZE_K, other=0.0)
        at = tl.load(at_ptrs, mask=offs_k[:, None] < M - k * BLOCK_SIZE_K, other=0.0)
        accumulator = tl.dot(a, at, accumulator)
        a_ptrs += BLOCK_SIZE_K * a_stride_c
        at_ptrs += BLOCK_SIZE_K * a_stride_c

    # Load block of A to add (corresponds to the current block of C)
    offs_am = m_idx + tl.arange(0, BLOCK_SIZE_M)
    offs_an = n_idx + tl.arange(0, BLOCK_SIZE_N)
    a_add_ptrs = A_ptr + (offs_am[:, None] * a_stride_r + offs_an[None, :] * a_stride_c)
    a_add_mask = (offs_am[:, None] < M) & (offs_an[None, :] < M)
    a_add = tl.load(a_add_ptrs, mask=a_add_mask, other=0.0).to(tl.float32)

    # Apply alpha and beta
    accumulator *= alpha
    accumulator += a_add * beta

    out_dtype = C_ptr.dtype.element_ty
    output = accumulator.to(out_dtype)

    # Store block of C
    offs_cm = m_idx + tl.arange(0, BLOCK_SIZE_M)
    offs_cn = n_idx + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = C_ptr + (offs_cm[:, None] * c_stride_r + offs_cn[None, :] * c_stride_c)
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < M)
    tl.store(c_ptrs, output, mask=c_mask)

    # Store block of C mirrored across the diagonal
    c_ptrs_t = C_ptr + (offs_cn[:, None] * c_stride_r + offs_cm[None, :] * c_stride_c)
    c_mask_t = (offs_cn[:, None] < M) & (offs_cm[None, :] < M)
    tl.store(c_ptrs_t, output.T, mask=c_mask_t)


def ba_plus_cAA(A: torch.Tensor, alpha: float, beta: float, out: torch.Tensor):
    """
    Launch Triton kernel to compute C = alpha * A @ A.T + beta * A
    """
    assert A.ndim == 2 or A.ndim == 3
    M, K = A.shape[-2:]
    assert M == K, "Input matrix must be square"
    assert out.size(-2) == M
    assert out.size(-1) == M

    batch_size = A.size(0) if A.ndim == 3 else 1
    input_batch_stride = A.stride(0) if A.ndim == 3 else 0
    output_batch_stride = out.stride(0) if out.ndim == 3 else 0

    grid = lambda meta: (
        batch_size
        * triton.cdiv(M, meta["BLOCK_SIZE_M"])
        * triton.cdiv(M, meta["BLOCK_SIZE_N"]),
    )
    ba_plus_cAA_kernel[grid](
        A_ptr=A,
        C_ptr=out,
        M=M,
        a_stride_b=input_batch_stride,
        a_stride_r=A.stride(-2),
        a_stride_c=A.stride(-1),
        c_stride_b=output_batch_stride,
        c_stride_r=out.stride(-2),
        c_stride_c=out.stride(-1),
        alpha=alpha,
        beta=beta,
    )
    return out


# Computed for num_iters=5, safety_factor=2e-2, cushion=2
polar_express_coeffs = [
    (8.156554524902461, -22.48329292557795, 15.878769915207462),
    (4.042929935166739, -2.808917465908714, 0.5000178451051316),
    (3.8916678022926607, -2.772484153217685, 0.5060648178503393),
    (3.285753657755655, -2.3681294933425376, 0.46449024233003106),
    (2.3465413258596377, -1.7097828382687081, 0.42323551169305323),
]


@torch.compile(
    dynamic=False, fullgraph=True
)  # Must use dynamic=False or else it's much slower
def polar_express(G: torch.Tensor, split_baddbmm: bool = False):
    """
    Polar Express Sign Method: https://arxiv.org/pdf/2505.16932
    by Noah Amsel, David Persson, Christopher Musco, Robert M. Gower.
    """
    X = G.bfloat16()
    if G.size(-2) > G.size(-1):
        X = X.mT

    # Ensure spectral norm is at most 1
    X = X / (X.norm(dim=(-2, -1), keepdim=True) * (1 + 2e-2) + 1e-6)

    # Allocate buffers
    X = X.contiguous()
    A = torch.empty((*X.shape[:-1], X.size(-2)), device=X.device, dtype=X.dtype)
    B = torch.empty_like(A)
    C = torch.empty_like(X)

    # Select batched vs unbatched
    if split_baddbmm:
        BX_matmul = torch.bmm if X.ndim > 2 else torch.mm
    else:
        aX_plus_BX = torch.baddbmm if X.ndim > 2 else torch.addmm

    # Perform the iterations
    for a, b, c in polar_express_coeffs:
        XXT(X, out=A)  # A = X @ X.mT
        ba_plus_cAA(A, alpha=c, beta=b, out=B)  # B = b * A + c * A @ A

        # Referencing X twice causes pytorch to make a defensive copy,
        # resulting in a cudaMemcpyAsync in baddbmm.
        # For large matrices (i.e., the mlp weights), it's faster to split
        # the operation into two kernels to avoid this.
        if split_baddbmm:
            BX_matmul(B, X, out=C)  # C = B @ X
            C.add_(X, alpha=a)  # C = C + a*X  (in-place, X only read)
        else:
            aX_plus_BX(X, B, X, beta=a, out=C)  # C = a * X + B @ X

        X, C = C, X  # Swap references to avoid unnecessary copies

    if G.size(-2) > G.size(-1):
        X = X.mT
    return X


# -----------------------------------------------------------------------------
# Compiled helpers for NorMuon by @chrisjmccormick


@torch.compile(dynamic=False, fullgraph=True)
def cautious_wd_and_update_inplace(p, v, wd_tensor, lr_tensor):
    """Cautious weight decay + parameter update. wd_tensor and lr_tensor are 0-D CPU tensors."""
    mask = (v * p) >= 0
    wd_factor = wd_tensor.to(p.dtype)
    lr_factor = lr_tensor.to(p.dtype)
    p.copy_(p - (p * mask * wd_factor * lr_factor) - (v * lr_factor))


@torch.compile(dynamic=False, fullgraph=True)
def plain_wd_and_update_inplace(p, v, wd_tensor, lr_tensor):
    """Plain decoupled weight decay + parameter update (model-track ablation)."""
    wd_factor = wd_tensor.to(p.dtype)
    lr_factor = lr_tensor.to(p.dtype)
    p.copy_(p - (p * wd_factor * lr_factor) - (v * lr_factor))


CAUTIOUS_WD = (
    True  # model track: plain decoupled weight decay (NorMuon and DistAdam) when False
)
_pending = []  # BF16-weight params whose grad arrived in this backward (accumulate_fp32)


@torch.compile(dynamic=False)
def _accumulate(mains, grads, fresh):
    for m, g, f in zip(mains, grads, fresh):
        m.copy_(g) if f else m.add_(g)


@torch.no_grad()
def _flush():
    ps = [p for p in _pending if p.main_grad is not None]
    for p in _pending:
        if p.main_grad is None:  # params without a flat buffer (DistAdam masters)
            p.main_grad = p.grad.float()
    if ps:
        _accumulate(
            [p.main_grad for p in ps],
            [p.grad for p in ps],
            [bool(getattr(p, "fresh", False)) for p in ps],
        )
    for p in _pending:
        p.grad, p.fresh = None, False
    _pending.clear()


CKPT = ""  # "mlp" | "block": recompute those activations in backward (training)


def accumulate_fp32(p):
    """BF16 weight: sum micro-batch grads in FP32 exactly as an FP32 weight's grad would be; batched at
    the end of backward (fresh: first micro-batch into NorMuon's flat buffer overwrites)."""
    if not _pending:
        torch.autograd.Variable._execution_engine.queue_callback(_flush)
    _pending.append(p)


NORMUON = (
    True  # model track: plain Muon, no second-moment variance reduction, when False
)


@torch.compile(dynamic=False, fullgraph=True)
def apply_normuon_variance_reduction(v_chunk, second_momentum_buffer, beta2, red_dim):
    """NorMuon variance reduction. Algebraically fuses the normalization steps to minimize memory ops."""
    v_mean = v_chunk.float().square().mean(dim=red_dim, keepdim=True)
    red_dim_size = v_chunk.size(red_dim)
    v_norm_sq = v_mean.sum(dim=(-2, -1), keepdim=True).mul_(red_dim_size)
    v_norm = v_norm_sq.sqrt_()
    second_momentum_buffer.lerp_(
        v_mean.to(dtype=second_momentum_buffer.dtype), 1 - beta2
    )
    step_size = second_momentum_buffer.clamp_min(1e-10).rsqrt_()
    scaled_sq_sum = (v_mean * red_dim_size) * step_size.float().square()
    v_norm_new = scaled_sq_sum.sum(dim=(-2, -1), keepdim=True).sqrt_()
    final_scale = step_size * (v_norm / v_norm_new.clamp_min_(1e-10))
    return v_chunk.mul_(final_scale.type_as(v_chunk))


# -----------------------------------------------------------------------------
# NorMuon optimizer


class NorMuon(torch.optim.Optimizer):
    """
    Muon - MomentUm Orthogonalized by Newton-schulz

    https://kellerjordan.github.io/posts/muon/

    Muon internally runs standard SGD-momentum, and then performs an orthogonalization post-
    processing step, in which each 2D parameter's update is replaced with the nearest orthogonal
    matrix. To efficiently orthogonalize each update, we use a Newton-Schulz iteration, which has
    the advantage that it can be stably run in bfloat16 on the GPU.

    Warning: This optimizer should not be used for the embedding layer, the final fully connected layer,
    or any {0,1}-D parameters; those should all be optimized by a standard method (e.g., AdamW).

    Differences from standard Muon:
    - Newton-Shulz is replaced with Polar Express for the orthogonalization step
    - NorMuon adds a low-rank variance estimator similar to Adafactor. https://arxiv.org/pdf/2510.05491
    - small 1D parameters handled here instead of in Adam
    - Cautious weight decay, a gated version of decoupled weight decay
    - Custom distributed sizing:
    The model stores all attn and mlp weights in the same shape, and then updates the view as
    needed on the forward pass. This enables attn and mlp weights to be contained within the same
    dist.reduce_scatter_tensor() call. The model architecture has been customized to enable
    (n_attn_layers+n_mlp_layers*2)%8==0 for batching across 8 GPUs with zero padding on mlp and attn.
    The scheduling is:
        1. reduce scatter attn_gate (10 params 6 padding params)
        2. reduce scatter attn/mlp round 1 (10 attn params 6 mlp params)
        3. reduce scatter attn/mlp round 2 (16 mlp params)
        4. wait on step 1, then compute update of 1 and schedule all gather
        5. wait on step 2, then compute update of 2 and schedule all gather
        6. wait on step 3, then compute update of 3 and schedule all gather
            GPUs receive [2 ATTN, 2 ATTN, 2 ATTN, 2 ATTN, 2 ATTN, 2 MLP, 2 MLP, 2 MLP]
            GPUs that receive params of type attn reshape before computing update
        7. wait on 4, then compute update of 4 and schedule all gather
        8. wait for each all gather to complete and update params
    Empirically, leading with small params provides an additional 0.2s improvement.
    """

    def __init__(
        self,
        params,
        lr=0.02,
        weight_decay=0.01,
        momentum=0.95,
        beta2=0.95,
        custom_sizing=True,
        group=None,
    ):
        defaults = dict(
            lr=lr, weight_decay=weight_decay, momentum=momentum, beta2=beta2
        )
        # group: a single-rank group for rank-local params (sharded MoE experts: whole experts per rank)
        self.group = group
        self.world_size = dist.get_world_size(group) if dist.is_initialized() else 1
        # custom sizing requires 8 GPUs and the upstream 16-layer matrices
        params = list(params)
        layout = dict(attn_gate=16, value_embed_gate=10, attn=16, mlp=32)
        if (
            custom_sizing
            and dist.get_world_size() == 8
            and Counter(p.label for p in params) == layout
        ):
            param_groups = self.generate_custom_param_groups(params)
        else:
            param_groups = self.generate_standard_param_groups(params)
        super().__init__(param_groups, defaults)
        # BF16 weights (p.master): FP32 master of this rank's shard from the FP32 init, FP32 grads in one
        # padded stacked buffer per group (reduce-scattered in place) and the BF16 params as rows of
        # another (all-gathered in place)
        rank = dist.get_rank(group) if dist.is_initialized() else 0
        self._flat, self._pflat = {}, {}
        for i, group in enumerate(self.param_groups):
            ps, lo = group["params"], rank * group["chunk_size"]
            if not getattr(ps[0], "master", False):
                continue
            if lo < len(ps):
                group["master"] = torch.stack(
                    [p.fp32 for p in ps[lo : lo + group["chunk_size"]]]
                )
            shape = (group["chunk_size"] * self.world_size, *ps[0].shape)
            self._flat[i] = torch.zeros(shape, dtype=torch.float32, device=ps[0].device)
            self._pflat[i] = torch.zeros(shape, dtype=ps[0].dtype, device=ps[0].device)
            for k, p in enumerate(ps):
                self._pflat[i][k].copy_(p.detach())
                p.data, p.main_grad, p.fresh = self._pflat[i][k], self._flat[i][k], True
                del p.fp32
        # by index: load_state_dict replaces the group dicts
        self._group_of = {
            p: i for i, g in enumerate(self.param_groups) for p in g["params"]
        }

    def reset(self):
        # expose a reset for clearing buffers
        for group in self.param_groups:
            if "momentum_buffer" in group:
                group["momentum_buffer"].zero_()
                group["second_momentum_buffer"].zero_()

    def generate_standard_param_groups(self, params):
        """
        Use this method if running on less than 8 GPU or experimenting with additional attn or mlp modules.
        Creates one param group per module.
        """
        groups = defaultdict(list)
        for param in params:
            groups[param.label].append(param)

        param_groups = []
        for module_name, group_params in groups.items():
            chunk_size = (len(group_params) + self.world_size - 1) // self.world_size
            param_groups.append(dict(params=group_params, chunk_size=chunk_size))

        return param_groups

    def generate_custom_param_groups(self, params):
        """
        Implementation requires that a single GPU does not receive both attn
        and mlp params when a param group is split across GPUs.
        """
        params_list = list(params)
        module_group_order = [
            "attn_gate",
            "value_embed_gate",
            "attn",
            "mlp",
        ]  # 16, 10, 16, 32
        group_sizes = [16, 10, 16, 16, 16]
        params_list.sort(key=lambda x: module_group_order.index(x.label))
        print0(len(params_list), console=True)
        idx = 0
        assert len(params_list) == sum(group_sizes)
        param_groups = []
        for size in group_sizes:
            chunk_size = (size + self.world_size - 1) // self.world_size
            group_params = params_list[idx : idx + size]
            param_groups.append(dict(params=group_params, chunk_size=chunk_size))
            idx += size

        return param_groups

    @torch.no_grad()
    def step(self):
        # Efficient distributed step by @YouJiacheng, @KonstantinWilleke, @alexrgilbert,
        # @adricarda, @tuttyfrutyee, @vdlad, @ryanyang0, @vagrawal, @varunneal, @chrisjmccormick
        rank = dist.get_rank(self.group)
        group_infos = []
        for group in self.param_groups:
            params: list[Tensor] = group["params"]
            if not params:
                continue

            chunk_size = group["chunk_size"]
            flat = self._flat.get(self._group_of[params[0]])
            if flat is not None:  # BF16 weights: FP32 grads already stacked
                for p in params:
                    p.fresh = True  # the next accumulation overwrites, after this reduce-scatter
                grad_chunk = torch.empty_like(flat[:chunk_size])
                reduce_future = dist.reduce_scatter_tensor(
                    grad_chunk, flat, op=dist.ReduceOp.AVG, group=self.group,
                    async_op=True,
                )
                group_infos.append(
                    dict(grad_chunk=grad_chunk, reduce_future=reduce_future)
                )
                continue
            padded_num_params = chunk_size * self.world_size

            stacked_grads = torch.empty(
                (padded_num_params, *params[0].shape),
                dtype=params[0].dtype,
                device=params[0].device,
            )
            for i, p in enumerate(params):
                stacked_grads[i].copy_(p.grad, non_blocking=True)
            if len(params) < padded_num_params:
                stacked_grads[len(params) :].zero_()

            grad_chunk = torch.empty_like(stacked_grads[:chunk_size])

            reduce_future = dist.reduce_scatter_tensor(
                grad_chunk, stacked_grads, op=dist.ReduceOp.AVG, group=self.group,
                async_op=True,
            )

            group_infos.append(dict(grad_chunk=grad_chunk, reduce_future=reduce_future))

        all_gather_infos = []
        # Second pass: wait for gradients, compute updates for the local shard of parameters,
        # and launch all async all_gather operations.
        for group, info in zip(self.param_groups, group_infos):
            info["reduce_future"].wait()

            params = group["params"]
            grad_chunk = info["grad_chunk"]
            # BF16 weights: FP32 grads, momentum and update math on the FP32 master
            master = getattr(params[0], "master", False)
            chunk_size = group["chunk_size"]
            padded_num_params = chunk_size * self.world_size

            start_idx = rank * chunk_size
            module_idx = start_idx if start_idx < len(params) else 0

            num_params = min(
                chunk_size, max(0, len(params) - start_idx)
            )  # num params for this rank

            if "momentum_buffer" not in group:
                group["momentum_buffer"] = torch.zeros_like(grad_chunk[:num_params])
            momentum_buffer = group["momentum_buffer"]
            # Apply momentum update to the persistent momentum buffer in-place
            momentum_buffer.lerp_(grad_chunk[:num_params], 1 - group["momentum"])
            updated_grads = grad_chunk[:num_params].lerp_(
                momentum_buffer, group["momentum"]
            )

            grad_shape = updated_grads.shape
            if params[module_idx].label == "attn":
                for p in params[module_idx : module_idx + num_params]:
                    assert p.label == "attn"

                updated_grads = updated_grads.view(
                    4 * grad_shape[0], grad_shape[1] // 4, grad_shape[2]
                )

            ref_param = params[module_idx]
            param_shape = ref_param.shape

            # The below shape-based heuristic assumes that matrices have their input along the
            # row dimension and their output along the columns. Gates are an exception.
            is_gate = "gate" in ref_param.label

            if "second_momentum_buffer" not in group:
                if is_gate:
                    group["second_momentum_buffer"] = torch.zeros_like(
                        updated_grads[..., :, :1]
                    )
                else:
                    group["second_momentum_buffer"] = (
                        torch.zeros_like(updated_grads[..., :, :1])
                        if param_shape[-2] >= param_shape[-1]
                        else torch.zeros_like(updated_grads[..., :1, :])
                    )
            second_momentum_buffer = group["second_momentum_buffer"]

            if "param_lr_cpu" not in group:
                # Define multipliers for ALL params in this group (global, not per-shard)
                lr_mults = []
                wd_mults = []
                for p in params:
                    # Increase learning rate for modules with larger inputs than outputs.
                    # This shape check also assumes rows=input, columns=output, so take care
                    # when changing memory layouts. @chrisjmccormick
                    shape = p.shape
                    if len(shape) >= 2:
                        shape_mult = max(1.0, shape[-2] / shape[-1]) ** 0.5
                    else:
                        shape_mult = 1.0
                    lr_mults.append(shape_mult * getattr(p, "lr_mul", 1.0))
                    wd_mults.append(getattr(p, "wd_mul", 1.0))
                # Define as cpu tensors to enable Inductor constant folding
                group["param_lr_cpu"] = torch.tensor(
                    lr_mults, dtype=torch.float32, device="cpu"
                )
                group["param_wd_cpu"] = torch.tensor(
                    wd_mults, dtype=torch.float32, device="cpu"
                )

            eff_lr_all = group["param_lr_cpu"] * group["lr"]
            eff_wd_all = group["param_wd_cpu"] * group["weight_decay"] * group["lr"]

            # Slice the portion corresponding to this rank's shard
            eff_lr_cpu = eff_lr_all[module_idx : module_idx + num_params]
            eff_wd_cpu = eff_wd_all[module_idx : module_idx + num_params]

            # Compute zeropower for the entire chunk in a single, batched call.
            if num_params == 0:
                v_chunk = updated_grads
            else:
                v_chunk = polar_express(  # 3D params (MoE experts): one matrix per leading index
                    updated_grads.flatten(0, -3), split_baddbmm=(ref_param.label == "mlp")
                ).view(updated_grads.shape)

            # Note that the head orientation in O is transposed relative to QKV, so red_dim
            # is 'incorrect' for O. However, correcting this showed no improvement. @chrisjmccormick
            red_dim = -1 if (is_gate or param_shape[-2] >= param_shape[-1]) else -2

            if NORMUON:
                v_chunk = apply_normuon_variance_reduction(
                    v_chunk, second_momentum_buffer, group["beta2"], red_dim
                )

            v_chunk = v_chunk.view(grad_shape)

            # # "Cautious" weight decay (https://arxiv.org/abs/2510.12402)
            updated_params = torch.empty_like(grad_chunk, dtype=params[0].dtype)
            if num_params > 0:
                # Work on a stacked copy to avoid touching original params; BF16 weights update the
                # persistent FP32 master of this rank's shard instead (ZeRO-1)
                param_chunk = (
                    group["master"]
                    if master
                    else torch.stack(params[module_idx : module_idx + num_params])
                )

                for local_idx in range(num_params):
                    (
                        cautious_wd_and_update_inplace
                        if CAUTIOUS_WD
                        else plain_wd_and_update_inplace
                    )(
                        param_chunk[local_idx],
                        v_chunk[local_idx],
                        eff_wd_cpu[local_idx],
                        eff_lr_cpu[local_idx],
                    )
            else:
                param_chunk = torch.zeros_like(v_chunk)

            updated_params[:num_params].copy_(param_chunk)
            if num_params < chunk_size:
                updated_params[num_params:].zero_()

            flat = self._pflat.get(self._group_of[params[0]])  # the params are its rows
            stacked_params = (
                torch.empty(
                    (padded_num_params, *param_shape),
                    dtype=updated_params.dtype,
                    device=updated_params.device,
                )
                if flat is None
                else flat
            )

            gather_future = dist.all_gather_into_tensor(
                stacked_params, updated_params, group=self.group, async_op=True
            )

            all_gather_infos.append(
                {
                    "gather_future": gather_future,
                    "stacked_params": stacked_params,
                    "orig_params": params,
                }
            )

        # Final pass: wait for all_gather to complete and copy results back into original parameter tensors.
        for info in all_gather_infos:
            info["gather_future"].wait()
            stacked_params = info["stacked_params"]
            orig_params = info["orig_params"]

            if stacked_params is self._pflat.get(self._group_of[orig_params[0]]):
                continue  # gathered in place
            unstacked_params = torch.unbind(stacked_params)
            for i, p in enumerate(orig_params):
                p.copy_(unstacked_params[i], non_blocking=True)


class DistAdam(torch.optim.Optimizer):
    def __init__(
        self,
        params,
        label_order: list[str],
        lr: float = 1e-3,
        betas: tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-8,
        weight_decay: float = 0.01,
    ):
        self.world_size = dist.get_world_size() if dist.is_initialized() else 1
        defaults = dict(lr=lr, betas=betas, eps=eps, weight_decay=weight_decay)
        params = list(params)
        # Group by label, with explicit ordering for execution control.
        params_by_label = defaultdict(list)
        for p in params:
            params_by_label[getattr(p, "label", None)].append(p)
        param_groups = []
        for label in label_order:
            if label in params_by_label:
                param_groups.append(dict(params=params_by_label[label]))
        # include any unlabeled params at the end (processed last)
        if None in params_by_label:
            param_groups.append(dict(params=params_by_label[None]))
        super().__init__(param_groups, defaults)
        # init state: small params (numel < 1024) use full-sized state, others use sharded
        rank = dist.get_rank() if dist.is_initialized() else 0
        for p in params:
            chunk = p if p.numel() < 1024 else p[: p.size(0) // self.world_size]
            dtype = torch.float32 if getattr(p, "fp32_state", False) else torch.bfloat16
            exp_avg = torch.zeros_like(chunk, dtype=dtype, device=p.device)
            self.state[p] = dict(
                step=0, exp_avg=exp_avg, exp_avg_sq=torch.zeros_like(exp_avg)
            )
            # BF16 weight: FP32 master of this rank's slice
            if getattr(p, "master", False):
                n, w = len(chunk), getattr(p, "fp32", p)
                self.state[p]["master"] = (
                    (w if p.numel() < 1024 else w[rank * n : (rank + 1) * n])
                    .float()
                    .clone()
                )
                if hasattr(p, "fp32"):
                    del p.fp32
        # DistributedAdam implementation by @vagrawal, @akash5474
        self.should_sync = False
        self._reduce_scatter_hooks = []
        self._reduce_scatter_futures = {}
        self.register_backward_hooks()

    def register_backward_hooks(self):
        for group in self.param_groups:
            for param in group["params"]:
                self._reduce_scatter_hooks.append(
                    param.register_post_accumulate_grad_hook(self._sync_gradient)
                )

    @torch.no_grad()
    def _sync_gradient(self, param):
        if not self.should_sync:
            return

        grad = param.grad
        if getattr(
            param, "master", False
        ):  # BF16 weight: this backward's grad folded in FP32
            if any(q is param for q in _pending):
                _flush()
            if getattr(param, "main_grad", None) is not None:
                grad, param.main_grad = param.main_grad, None
        if param.numel() < 1024:
            # Small params: use all_reduce (no scatter/gather needed)
            self._reduce_scatter_futures[param] = (
                dist.all_reduce(grad, op=dist.ReduceOp.AVG, async_op=True),
                grad,
            )
        else:
            rank_size = grad.shape[0] // self.world_size
            if grad is not None:
                grad_slice = torch.empty_like(grad[:rank_size])
                self._reduce_scatter_futures[param] = (
                    dist.reduce_scatter_tensor(
                        grad_slice, grad, op=dist.ReduceOp.AVG, async_op=True
                    ),
                    grad_slice,
                )

    def copy_lm_to_embed(self):
        # run at 1/6 of training
        # by label, not group position: other Adam groups (e.g. the model track's board) may follow
        by_label = {p.label: p for g in self.param_groups for p in g["params"]}
        lm_head, embed = by_label["lm_head"], by_label["embed"]
        lm_head_state = self.state[lm_head]
        embed_state = self.state[embed]
        embed_state["step"] = lm_head_state["step"]
        embed_state["exp_avg"] = lm_head_state["exp_avg"].clone()
        embed_state["exp_avg_sq"] = lm_head_state["exp_avg_sq"].clone()
        embed.data.copy_(lm_head.data)

    @torch.compile
    @torch.no_grad()
    def step(self):
        rank = dist.get_rank()
        all_gather_futures = []  # c10d Works: Work.wait() also releases NCCL's stashed tensors

        for group in self.param_groups:
            beta1, beta2 = group["betas"]
            eps = group["eps"]
            wd = group["weight_decay"]
            for param in group["params"]:
                if param not in self._reduce_scatter_futures:
                    continue

                fut, g_slice = self._reduce_scatter_futures[param]
                fut.wait()

                is_small = param.numel() < 1024
                if is_small:
                    # Small params: g_slice is actually full grad, p_slice is full param
                    p_slice = param
                else:
                    rank_size = param.shape[0] // self.world_size
                    p_slice = param[rank * rank_size : (rank + 1) * rank_size]

                lr = group["lr"] * getattr(param, "lr_mul", 1.0)
                state = self.state[param]
                out, p_slice = p_slice, state.get("master", p_slice)

                exp_avg = state["exp_avg"]
                exp_avg_sq = state["exp_avg_sq"]
                state["step"] += 1
                t = state["step"]
                # update running averages
                exp_avg.mul_(beta1).add_(g_slice, alpha=1 - beta1)
                exp_avg_sq.mul_(beta2).addcmul_(g_slice, g_slice, value=1 - beta2)
                # bias corrections
                bias1 = 1 - beta1**t
                bias2 = 1 - beta2**t
                # compute step
                denom = exp_avg_sq.sqrt().add_(eps)
                step_size = lr * (bias2**0.5 / bias1)
                update = exp_avg.div(denom).mul_(step_size)
                # lr as weight decay schedule
                eff_weight_decay = lr * wd * getattr(param, "wd_mul", 1.0)
                if CAUTIOUS_WD:
                    mask = (update * p_slice) > 0
                    update.addcmul_(p_slice, mask, value=eff_weight_decay * lr)
                else:
                    update.add_(p_slice, alpha=eff_weight_decay * lr)

                p_slice.add_(other=update, alpha=-1.0)
                if out is not p_slice:
                    out.copy_(p_slice)

                if not is_small:
                    all_gather_futures.append(
                        dist.all_gather_into_tensor(param, out, async_op=True)
                    )

        self._reduce_scatter_futures.clear()
        for work in all_gather_futures:
            work.wait()


# -----------------------------------------------------------------------------
# PyTorch nn.Module definitions for the model


def norm(x: Tensor):
    return F.rms_norm(x, (x.size(-1),))


class CastedLinear(nn.Linear):
    def __init__(
        self,
        in_features: int,
        out_features: int,
        use_fp8=False,
        x_s=1.0,
        w_s=1.0,
        grad_s=1.0,
    ):
        super().__init__(in_features, out_features, bias=False)
        self.use_fp8 = False  # turn off fp8 for now -> requires tuning of scales which hasnt been done on medium track
        self.x_s = x_s
        self.w_s = w_s
        self.grad_s = grad_s

    def reset_parameters(self) -> None:
        with torch.no_grad():
            self.weight.zero_()  # @Grad62304977 and others

    def forward(self, x: Tensor):
        if self.use_fp8 and self.training:
            _x = x.flatten(0, -2)
            out: Tensor = torch.ops.nanogpt.mm(
                _x, self.weight, x_s=self.x_s, w_s=self.w_s, grad_s=self.grad_s
            )[0]
            return out.reshape(*x.shape[:-1], -1)
        else:
            return F.linear(x, self.weight.type_as(x))


# -----------------------------------------------------------------------------
# PyTorch nn.Module definitions for the model


# yarn implementation @classiclarryd
class Yarn(nn.Module):
    def __init__(self, head_dim, max_seq_len):
        super().__init__()
        self.head_dim = head_dim
        self.max_seq_len = max_seq_len
        self.fp32 = False  # model track: FP32 cos/sin tables (default BF16)
        self.full = (
            False  # model track: rotate every head dim (default: half-truncated)
        )
        self.base_scale = 0.1  # attention scale restored by reset()
        self.reset()

    def reset(self):
        quarter = self.head_dim // 4
        angular_freq = (1 / 1024) ** torch.linspace(
            0,
            1,
            steps=2 * quarter if self.full else quarter,
            dtype=torch.float32,
            device=device,
        )
        if not self.full:
            # half-truncate RoPE by @YouJiacheng (w/ base freq tuning)
            angular_freq = torch.cat([angular_freq, angular_freq.new_zeros(quarter)])
        t = torch.arange(self.max_seq_len, dtype=torch.float32, device=device)
        theta = torch.outer(t, angular_freq)
        dt = torch.float32 if self.fp32 else torch.bfloat16
        self.cos = nn.Buffer(theta.cos().to(dt), persistent=False)
        self.sin = nn.Buffer(theta.sin().to(dt), persistent=False)
        self.angular_freq = angular_freq
        # start with 0.1, inspired by 0.12 from @leloykun and learnable scalars used by @brendanh0gan https://x.com/hi_tysam/status/1879693583898591283
        self.attn_scale = self.base_scale

    def apply(self, old_window: int, new_window: int, alpha: int = 1, beta: int = 32):
        rotations = args.block_size * old_window * self.angular_freq / (2 * torch.pi)
        scaling_factor = old_window / new_window
        interpolation_weight = torch.clamp((rotations - alpha) / (beta - alpha), 0, 1)
        self.angular_freq *= scaling_factor + interpolation_weight * (
            1 - scaling_factor
        )
        t = torch.arange(
            self.max_seq_len, dtype=torch.float32, device=self.angular_freq.device
        )
        theta = torch.outer(t, self.angular_freq)
        self.cos.copy_(theta.cos())
        self.sin.copy_(theta.sin())
        self.attn_scale *= 0.2 * math.log(new_window / old_window) + 1


def rotary(x_BTHD: Tensor, cos: Tensor, sin: Tensor):
    assert cos.size(0) >= x_BTHD.size(-3)
    cos, sin = (
        cos[None, : x_BTHD.size(-3), None, :],
        sin[None, : x_BTHD.size(-3), None, :],
    )
    x = x_BTHD.to(cos.dtype)  # FP32 tables rotate in FP32; a no-op for the default BF16
    x1, x2 = x.chunk(2, dim=-1)
    y1 = x1 * cos + x2 * sin
    y2 = x1 * (-sin) + x2 * cos
    return torch.cat((y1, y2), 3).type_as(x_BTHD)


@dataclass
class AttnArgs:
    ve: torch.Tensor
    sa_lambdas: torch.Tensor
    seqlens: torch.Tensor
    bm_size: int
    cos: torch.Tensor
    sin: torch.Tensor
    attn_scale: float
    key_offset: bool


# Attention backend is supplied by modded_medium.py.


class CausalSelfAttention(nn.Module):
    def __init__(self, dim: int, head_dim: int, num_heads: int, layer_idx: int):
        super().__init__()
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.dim = dim
        self.hdim = num_heads * head_dim
        self.qk_norm = self.gates = True  # model-track ablations
        self.diff = None  # modded_diffattn.DiffLambda: differential attention

        assert self.hdim == self.dim, "num_heads * head_dim must equal model_dim"
        std = self.dim**-0.5
        bound = (3**0.5) * std  # improved init scale by @YouJiacheng
        # merged QKVO weights: suggested by many, implemented by @fernbear.bsky.social, and further improved by @YouJiacheng
        # https://x.com/hi_tysam/status/1879699187107033311
        # Simplified layout by @chrisjmccormick
        self.qkvo_w = nn.Parameter(torch.empty(self.dim * 4, self.hdim))
        # label all modules for explicit optimizer grouping
        self.qkvo_w.label = "attn"

        with torch.no_grad():
            self.qkvo_w[: self.dim * 3].uniform_(-bound, bound)  # init QKV weights
            self.qkvo_w[self.dim * 3 :].zero_()  # init O weights to zero

        # sparse gated attention to enable context based no-op by @classiclarryd
        self.attn_gate = CastedLinear(16, num_heads)
        self.attn_gate.weight.label = "attn_gate"
        self.attn_gate.weight.lr_mul = 0.1

        # only include gates on layers with value embeds used on forward pass
        if layer_idx < min(
            5, args.num_layers // 2
        ) or layer_idx >= args.num_layers - min(5, args.num_layers // 2):
            self.value_embed_gate = CastedLinear(16, num_heads)
            self.value_embed_gate.weight.label = "value_embed_gate"
            self.value_embed_gate.weight.lr_mul = 0.1

    def forward(self, x: Tensor, attn_args: AttnArgs):
        B, T = x.size(0), x.size(1)  # batch size, sequence length
        assert B == 1, "varlen sequences requires B == 1"
        assert T % 16 == 0
        # unpack attention args
        cos, sin = attn_args.cos, attn_args.sin
        ve, sa_lambdas, key_offset = (
            attn_args.ve,
            attn_args.sa_lambdas,
            attn_args.key_offset,
        )
        seqlens, attn_scale, bm_size = (
            attn_args.seqlens,
            attn_args.attn_scale,
            attn_args.bm_size,
        )

        q, k, v = (
            F.linear(x, sa_lambdas[0] * self.qkvo_w[: self.dim * 3].type_as(x))
            .view(B, T, 3 * self.num_heads, self.head_dim)
            .chunk(3, dim=-2)
        )
        if self.qk_norm:
            q, k = norm(q), norm(k)  # QK norm @Grad62304977
        q, k = rotary(q, cos, sin), rotary(k, cos, sin)
        if key_offset:
            # shift keys forward for the stationary head dims. Enables 1-layer induction.
            same = seqlens.same_previous[1:][None, :, None, None]
            # Keep a game's first key intact; never import the preceding game.
            k = k.clone()
            k[:, 1:, :, self.head_dim // 4 : self.head_dim // 2] = torch.where(
                same,
                k[:, :-1, :, self.head_dim // 4 : self.head_dim // 2].clone(),
                k[:, 1:, :, self.head_dim // 4 : self.head_dim // 2],
            )
            k[:, 1:, :, 3 * self.head_dim // 4 :] = torch.where(
                same,
                k[:, :-1, :, 3 * self.head_dim // 4 :].clone(),
                k[:, 1:, :, 3 * self.head_dim // 4 :],
            )
        if ve is not None:
            ve_gate_out = 2 * torch.sigmoid(
                self.value_embed_gate(x[..., : self.value_embed_gate.weight.size(-1)])
            ).view(B, T, self.num_heads, 1)
            if not self.gates:  # identity gate; the gate weight keeps a (zero) gradient
                ve_gate_out = ve_gate_out * 0 + 1
            v = v + ve_gate_out * ve.view_as(v)  # @ KoszarskyB & @Grad62304977

        max_len = (
            args.train_max_seq_len
            if self.training
            else (args.val_batch_size // (grad_accum_steps * world_size))
        )

        # use flash_attn over flex_attn @varunneal. flash_attn_varlen suggested by @YouJiacheng
        attend = lambda q, k, v: medium_attention(q, k, v, seqlens, bm_size, attn_scale)
        y = (
            attend(q, k, v)
            if self.diff is None
            else diff_attention(q, k, v, self.diff(), self.diff.init, attend)
        )
        y = y.view(B, T, self.num_heads, self.head_dim)
        gate = torch.sigmoid(
            self.attn_gate(x[..., : self.attn_gate.weight.size(-1)])
        ).view(B, T, self.num_heads, 1)
        y = y * (
            gate if self.gates else gate * 0 + 0.5
        )  # sigma(0): the default gate at init
        y = y.contiguous().view(
            B, T, self.num_heads * self.head_dim
        )  # re-assemble all head outputs side by side
        y = F.linear(
            y, sa_lambdas[1] * self.qkvo_w[self.dim * 3 :].type_as(y)
        )  # sa_lambdas[1] pre-multiplied to O @shenberg
        return y


class MLP(nn.Module):
    def __init__(self, dim: int, kind: str = "relu2"):
        super().__init__()
        self.kind = kind  # relu2 | gelu | swiglu (model track)
        hdim = swiglu_hidden(dim) if kind == "swiglu" else 4 * dim
        # Transposed layout to match attention weights
        self.c_fc = nn.Parameter(
            torch.empty(hdim * (2 if kind == "swiglu" else 1), dim)
        )
        self.c_proj = nn.Parameter(torch.empty(hdim, dim))
        # label all modules for explicit optimizer grouping; NorMuon stacks a label's params, so
        # SwiGLU's differently shaped projection gets its own label
        self.c_fc.label = "mlp"
        self.c_proj.label = "mlp_proj" if kind == "swiglu" else "mlp"
        self.c_proj.lr_mul = 2.0

        std = 0.5 * (dim**-0.5)
        bound = (3**0.5) * std  # improved init scale by @YouJiacheng
        with torch.no_grad():
            self.c_fc.uniform_(-bound, bound)
            self.c_proj.zero_()  # zero init suggested by @Grad62304977

    def forward(self, x: Tensor):
        x = F.linear(x, self.c_fc.type_as(x))
        if self.kind == "swiglu":
            a, b = x.chunk(2, dim=-1)
            x = F.silu(a) * b
        elif self.kind == "gelu":
            x = F.gelu(x)
        else:
            x = F.relu(
                x
            ).square()  # https://arxiv.org/abs/2109.08668v2; ~1-2% better than GELU; suggested by @SKYLINEZ007 and @Grad62304977
        x = F.linear(x, self.c_proj.T.type_as(x))
        return x


class Block(nn.Module):
    def __init__(
        self,
        dim: int,
        head_dim: int,
        num_heads: int,
        layer_idx: int,
        mlp: str = "relu2",
        moe: tuple | None = None,
    ):
        super().__init__()
        self.attn = CausalSelfAttention(dim, head_dim, num_heads, layer_idx)
        # model track: MoE (modded_arch.moe_dims) after a dense first layer, as in DeepSeek-V3
        self.mlp = MoE(dim, *moe) if moe and layer_idx else MLP(dim, mlp)

    def forward(self, x: Tensor, attn_args: AttnArgs):
        if CKPT == "block" and self.training:
            return torch.utils.checkpoint.checkpoint(
                self._forward, x, attn_args, use_reentrant=False
            )
        return self._forward(x, attn_args)

    def _forward(self, x: Tensor, attn_args: AttnArgs):
        x = x + self.attn(norm(x), attn_args)
        if CKPT == "mlp" and self.training:
            return x + torch.utils.checkpoint.checkpoint(
                lambda h: self.mlp(norm(h)), x, use_reentrant=False
            )
        return x + self.mlp(norm(x))


# -----------------------------------------------------------------------------
# The main model


def next_multiple_of_n(v: float | int, *, n: int):
    return next(x for x in range(n, int(v) + 1 + n, n) if x >= v)


@dataclass
class ForwardScheduleConfig:
    mtp_weights: torch.Tensor
    ws_short: int
    ws_long: int


class GPT(nn.Module):
    def __init__(
        self,
        vocab_size: int,
        num_layers: int,
        num_heads: int,
        head_dim: int,
        model_dim: int,
        max_seq_len: int,
        mlp: str = "relu2",
        untie_ve: bool = False,
        moe: tuple | None = None,
    ):
        super().__init__()
        self.num_layers = num_layers
        vocab_size = next_multiple_of_n(vocab_size, n=128)

        self.smear_gate = CastedLinear(16, 1)
        self.smear_gate.weight.label = "smear_gate"
        self.smear_gate.weight.lr_mul = 0.01
        self.smear_gate.weight.wd_mul = 0.0

        self.skip_gates = nn.ModuleList([CastedLinear(16, 1) for _ in range(3)])
        for sg in self.skip_gates:
            sg.weight.label = "skip_gate"
            sg.weight.lr_mul = 0.01
            sg.weight.wd_mul = 0.0

        # token value embeddings by @KoszarskyB - inspired by @Grad62304977's value residual implementation following https://arxiv.org/abs/2410.17897
        # value embedding code simplification inspired by @ragulpr https://github.com/KellerJordan/modded-nanogpt/pull/78
        self.value_embeds = nn.ModuleList(
            [
                nn.Embedding(vocab_size, model_dim)
                for _ in range(min(5, num_layers // 2) * (2 if untie_ve else 1))
            ]
        )
        self.untie_ve = untie_ve  # model track: one table per value-embedding layer
        for embed in self.value_embeds:
            nn.init.zeros_(embed.weight)
        for ve in self.value_embeds:
            ve.weight.label = "value_embed"
        self.blocks = nn.ModuleList(
            [
                Block(model_dim, head_dim, num_heads, i, mlp, moe)
                for i in range(num_layers)
            ]
        )
        self.yarn = Yarn(head_dim, max_seq_len)
        # there are only 50257 unique GPT-2 tokens; we extend to nearest multiple of 128 for efficiency.
        # suggested to me by @Grad62304977. this originates from Karpathy's experiments.
        use_fp8 = not os.environ.get("DISABLE_FP8", False)

        self.lm_head = CastedLinear(
            model_dim,
            vocab_size,
            use_fp8=use_fp8,
            x_s=100 / 448,
            w_s=1.6 / 448,
            grad_s=0.75 / 448,
        )
        nn.init.normal_(self.lm_head.weight, mean=0, std=0.005)
        self.lm_head.weight.label = "lm_head"

        self.embed = nn.Embedding(vocab_size, model_dim)
        self.embed.weight.label = "embed"

        self.embed2 = nn.Embedding(vocab_size, model_dim)
        self.embed2.weight.label = "embed2"

        # x0_lambdas separated out for different optimizer treatment (no beta smoothing)
        self.x0_lambdas = nn.Parameter(torch.zeros(2 * num_layers))
        self.x0_lambdas.label = "x0_lambdas"
        self.x0_lambdas.lr_mul = 5.0
        self.x0_lambdas.wd_mul = 0.0

        pad = (
            -num_layers * 3 - 5
        ) % dist.get_world_size()  # updated: 3*num_layers instead of 4*
        self.scalars = nn.Parameter(
            torch.cat(
                [
                    1.05
                    * torch.ones(
                        num_layers
                    ),  # resid lambdas. 1.05 init such that layer i weight is i^(num_layers-i).
                    *[
                        torch.tensor([0.5, 1.0]) for _ in range(num_layers)
                    ],  # SA lambdas
                    torch.zeros(1),  # smear_lambda
                    0.5 * torch.ones(1),  # backout_lambda
                    -1.5 * torch.ones(3),  # skip_lambdas -> σ(-1.5) ≈ 0.18
                    torch.ones(pad),
                ]
            )
        )

        self.scalars.label = "scalars"
        # set learning rates
        for param in self.value_embeds.parameters():
            param.lr_mul = 75.0
            param.wd_mul = 5.0
        for param in self.embed.parameters():
            param.wd_mul = 150.0
        for param in self.embed2.parameters():
            param.lr_mul = 75.0
            param.wd_mul = 5.0
        for param in self.lm_head.parameters():
            param.wd_mul = 150.0
        self.scalars.lr_mul = 5.0
        self.scalars.wd_mul = 0.0

        # start training with tied embed/lm_head
        self.split_embed = False

        # Embedding of the mover's time-left bucket (0 = no clock, fixed at zero), added to the token
        # embedding when use_clock. Zero init keeps a fresh model clock-blind; created last so every
        # other parameter's initialization is unchanged.
        self.use_clock = False
        self.clock_embed = nn.Embedding(64, model_dim, padding_idx=0)
        nn.init.zeros_(self.clock_embed.weight)
        self.clock_embed.weight.label = "embed2"
        self.clock_embed.weight.lr_mul = 75.0
        self.clock_embed.weight.wd_mul = 5.0
        # Embedding of the mover's rating bucket (50 Elo wide, 0 = none), same treatment as the clock.
        self.use_elo = False
        self.elo_embed = nn.Embedding(64, model_dim, padding_idx=0)
        nn.init.zeros_(self.elo_embed.weight)
        self.elo_embed.weight.label = "embed2"
        self.elo_embed.weight.lr_mul = 75.0
        self.elo_embed.weight.wd_mul = 5.0
        # Continuous clock features (use_feats): three raw-seconds channels -> 54 log-Fourier
        # features -> model_dim, zero init; rows 54..63 pad dim 0 for optimizer sharding.
        self.use_feats = False
        self.feat_embed = nn.Embedding(64, model_dim)
        nn.init.zeros_(self.feat_embed.weight)
        self.feat_embed.weight.label = "embed2"
        self.feat_embed.weight.lr_mul = 75.0
        self.feat_embed.weight.wd_mul = 5.0
        # Model-track ablations of inherited speedrun components (default on).
        self.use_value_embeds = self.use_skips = self.use_smear = True
        self.doc_rope = (
            False  # rotary position = index in the game instead of the packed batch
        )
        self.use_x0 = self.use_embed2 = self.softcap = self.use_key_offset = True
        self.aux_detach = (
            None  # first aux-head row, when those rows get stop-gradient features
        )
        self.fp32_embed = False  # FP32 embedding/head state: cast lookups to BF16
        self.board = None  # modded_board branch, added at every position when set

    def forward(
        self,
        input_seq: Tensor,
        target_seq: Tensor,
        seqlens: Tensor,
        schedule_cfg: ForwardScheduleConfig,
        clock_seq: Tensor | None = None,
        elo_seq: Tensor | None = None,
        feat_seq: Tensor | None = None,
    ):
        assert input_seq.ndim == 1

        # unpack schedule_cfg
        mtp_weights, ws_short, ws_long = (
            schedule_cfg.mtp_weights,
            schedule_cfg.ws_short,
            schedule_cfg.ws_long,
        )

        # set configs
        skip_connections = []
        skip_in = [i * self.num_layers // 16 for i in (2, 4, 6)]
        skip_out = [9 * self.num_layers // 16 + i for i in range(3)]
        x_backout = None
        backout_layer = skip_out[-1]

        # set lambdas
        resid_lambdas = self.scalars[: 1 * self.num_layers]
        x0_lambdas = self.x0_lambdas.view(-1, 2)
        if not self.use_x0:  # drop x0 re-injection; keep the x02 column
            x0_lambdas = torch.stack((x0_lambdas[:, 0] * 0, x0_lambdas[:, 1]), 1)
        sa_lambdas = self.scalars[1 * self.num_layers : 3 * self.num_layers].view(-1, 2)
        smear_lambda = self.scalars[3 * self.num_layers]
        backout_lambda = self.scalars[3 * self.num_layers + 1]
        skip_lambdas = self.scalars[3 * self.num_layers + 2 : 3 * self.num_layers + 5]

        # set block masks and key shift
        short_bm = ws_short * args.block_size
        long_bm = ws_long * args.block_size
        long_layers = {round(i * (self.num_layers - 1) / 15) for i in (0, 4, 11, 15)}
        bm_sizes = [
            long_bm if i in long_layers else short_bm for i in range(self.num_layers)
        ]
        assert len(bm_sizes) == self.num_layers
        key_offset = [
            b == long_bm and self.use_key_offset for b in bm_sizes
        ]  # apply partial key offset to long windows

        # weight-tied: use lm_head.weight for embedding lookup (or separate embed after split)
        if self.split_embed:
            x = self.embed(input_seq)
        else:
            x = F.embedding(input_seq, self.lm_head.weight)
        if self.fp32_embed:
            x = x.bfloat16()
        if self.use_clock:
            ids = torch.zeros_like(input_seq) if clock_seq is None else clock_seq
            x = x + self.clock_embed(ids)
        if self.use_elo:
            ids = torch.zeros_like(input_seq) if elo_seq is None else elo_seq
            x = x + self.elo_embed(ids)
        if self.use_feats and feat_seq is not None:
            t = feat_seq[:, : self.use_feats].float()
            v = torch.log1p(t.clamp(min=0))[..., None] / 10
            w = torch.pi * 2.0 ** torch.arange(8, device=t.device)
            f = torch.cat(
                (torch.sin(v * w), torch.cos(v * w), v, torch.ones_like(v)), -1
            )
            f = (f * (t >= 0)[..., None]).flatten(1)  # absent values (-1) give zeros
            f = F.pad(f, (0, 64 - f.shape[1]))
            x = x + f.type_as(x) @ self.feat_embed.weight.type_as(x)
        if self.board is not None:
            x = x + self.board(seqlens.board, x.dtype)
        ve = [value_embed(input_seq) for value_embed in self.value_embeds]
        if self.fp32_embed:
            ve = [v.bfloat16() for v in ve]
        if (
            not self.use_value_embeds
        ):  # ablated by zero so every parameter keeps a gradient
            ve = [v * 0 for v in ve]
        # 012 ... 012 structure on token value embeddings by @YouJiacheng, improved on @leloykun's U-net structure
        # dropping first layer updates this to .12 ... 012
        k = len(ve) // 2 if self.untie_ve else len(ve)
        ve = ve[:k] + [None] * (self.num_layers - 2 * k) + ve[-k:]
        assert len(ve) == self.num_layers

        # smear token embed forward 1 position @classiclarryd
        smear_gate_out = smear_lambda * torch.sigmoid(
            self.smear_gate(x[1:, : self.smear_gate.weight.size(-1)])
        )
        if not self.use_smear:
            smear_gate_out = smear_gate_out * 0
        x = torch.cat(
            [x[:1], x[1:] + smear_gate_out * x[:-1] * seqlens.same_previous[1:, None]]
        )
        x = x0 = norm(x[None])

        e2 = self.embed2(input_seq)
        x02 = norm((e2.bfloat16() if self.fp32_embed else e2)[None])
        if not self.use_embed2:
            x02 = x02 * 0

        cos, sin = self.yarn.cos, self.yarn.sin
        if self.doc_rope:
            cos, sin = cos[seqlens.positions], sin[seqlens.positions]
        skip_idx = 0
        for i in range(self.num_layers):
            attn_args = AttnArgs(
                ve=ve[i],
                sa_lambdas=sa_lambdas[i],
                seqlens=seqlens,
                bm_size=bm_sizes[i],
                cos=cos,
                sin=sin,
                attn_scale=self.yarn.attn_scale,
                key_offset=key_offset[i],
            )
            if i in skip_out:
                skip_gate_out = (
                    torch.sigmoid(skip_lambdas[skip_idx])
                    * 2
                    * torch.sigmoid(
                        self.skip_gates[skip_idx](
                            x0[..., : self.skip_gates[skip_idx].weight.size(-1)]
                        )
                    )
                )
                skip_idx += 1
                skip = skip_connections.pop()
                x = x + skip_gate_out * (skip if self.use_skips else skip * 0)
            if i == 0:
                x = (resid_lambdas[0] + x0_lambdas[0, 0]) * x + x0_lambdas[0, 1] * x02
            else:
                x = (
                    resid_lambdas[i] * x
                    + x0_lambdas[i, 0] * x0
                    + x0_lambdas[i, 1] * x02
                )
            x = self.blocks[i](x, attn_args)
            if i in skip_in:
                skip_connections.append(x)
            if i == backout_layer:
                x_backout = x

        # back out contributions from first 2/3 layers that are only required for downstream context and not direct prediction
        x -= backout_lambda * (x_backout if self.use_skips else x_backout * 0)
        x = norm(x)

        logits = self.lm_head(x)
        if (
            self.aux_detach
        ):  # head rows from this index on (the aux heads) see stop-gradient features
            k = self.aux_detach
            aux = F.linear(x.detach(), self.lm_head.weight[k:].type_as(x))
            logits = torch.cat((logits[..., :k], aux), -1)
        if not self.softcap:
            return logits
        return 23 * torch.sigmoid((logits + 5) / 7.5)


# -----------------------------------------------------------------------------
# Distributed data loader


def get_bs(step: int):
    if step >= args.num_scheduled_iterations:
        return args.train_bs_extension
    x = step / args.num_scheduled_iterations
    bs_idx = int(len(args.train_bs_schedule) * x)
    return args.train_bs_schedule[bs_idx]


def get_ws(step: int):
    # set short window size to half of long window size
    # Higher ws on "extension" steps
    if step >= args.num_scheduled_iterations:
        return args.ws_final // 2, args.ws_final
    x = step / args.num_scheduled_iterations
    assert 0 <= x < 1
    ws_idx = int(len(args.ws_schedule) * x)
    return min(11, args.ws_schedule[ws_idx] // 2), args.ws_schedule[ws_idx]


# learning rate schedule: tied to batch size schedule, with cooldown at the end.
def get_lr(step: int):
    if step > args.num_scheduled_iterations:
        return 0.1
    lr_max = 1.0
    x = step / args.num_scheduled_iterations
    if x > 1 / 12:
        lr_max = 1.52  # (16/8)**0.6
    if x > 2 / 12:
        lr_max = 1.73  # (24/8)**0.5
    if x > 3 / 12:
        lr_max = 2.0
    if x >= 1 - args.cooldown_frac:
        w = (1 - x) / args.cooldown_frac
        lr = lr_max * w + (1 - w) * 0.1
        return lr
    return lr_max


def get_muon_momentum(
    step: int,
    muon_warmup_steps=300,
    muon_cooldown_steps=50,
    momentum_min=0.85,
    momentum_max=0.95,
):
    # warmup phase: linearly increase momentum from min to max
    # cooldown phase: linearly decrease momentum from max to min
    momentum_cd_start = args.num_iterations - muon_cooldown_steps
    if step < muon_warmup_steps:
        frac = step / muon_warmup_steps
        momentum = momentum_min + frac * (momentum_max - momentum_min)
    elif step > momentum_cd_start:
        frac = (step - momentum_cd_start) / muon_cooldown_steps
        momentum = momentum_max - frac * (momentum_max - momentum_min)
    else:
        momentum = momentum_max
    return momentum


class TrainingManager:
    """
    Manages three optimizers for Adam embed/lm_head, Adam scalars, and Muon weight matrices.
    Notable Features:
        1. Scalars are given higher momentum terms to smooth learning @ChrisJMcCormick
        2. Scalar weights are temporarily frozen during batch size or window size updates @ChrisJMcCormick
        3. Adam optimizers are only stepped on odd steps @classiclarryd
        4. Adam optimizers have hooks to start gradient communication during backwards pass @akash5474
        5. Muon has a linear momentum warmup and cooldown schedule
        6. Learning rates follow a linear decay schedule
        7. Embed/lm_head weights and optimizer state splits at 2/3 of training @classiclarryd

    Manages model architecture, data, and target that changes during training
    Notable Features:
        1. Multi Token Prediction schedule of [1, 0.5, 0.25->0] -> [1, 0.5->0] -> [1] @varunneal
        2. Sliding Attention window schedule of [1,3] -> [3,7] -> [5,11] -> [6,13]
        3. YaRN updates to RoPE on window changes
        4. Split embed and lm head at 2/3 of training
        5. Batch size schedule of 8 -> 16 -> 24
        6. Post training extension of long windows from 13 to 20
    """

    def __init__(self, model):
        self.mtp_weights_schedule = self._build_mtp_schedule()
        self.model = model

        adam_labels = [
            "lm_head",
            "value_embed",
            "smear_gate",
            "skip_gate",
            "x0_lambdas",
            "embed2",
            "embed",
            "board",
            "router",
            "diff",
        ]
        scalar_labels = ["scalars"]
        muon_labels = ["attn_gate", "value_embed_gate", "attn", "mlp", "mlp_proj"]
        muon_labels += ["moe", "moe_up", "mlp_shared", "mlp_shared_up"]
        self.moe = [m for m in model.modules() if isinstance(m, MoE)]
        # model track: AdamW (base lr model.matrix_adam) for the attention / MLP matrices
        matrix_labels = (
            ["attn", "mlp", "mlp_proj"] if getattr(model, "matrix_adam", 0) else []
        )
        muon_labels = [l for l in muon_labels if l not in matrix_labels]
        matrix_params = [
            p for p in model.parameters() if getattr(p, "label", None) in matrix_labels
        ]
        adam_params = [
            p for p in model.parameters() if getattr(p, "label", None) in adam_labels
        ]
        scalar_params = [
            p for p in model.parameters() if getattr(p, "label", None) in scalar_labels
        ]
        muon_params = [
            p for p in model.parameters() if getattr(p, "label", None) in muon_labels
        ]
        local_labels = ["moe_sh", "moe_up_sh"]  # sharded experts: rank-local NorMuon
        local_params = [
            p for p in model.parameters() if getattr(p, "label", None) in local_labels
        ]
        assert set(getattr(p, "label", None) for p in model.parameters()) <= set(
            adam_labels + scalar_labels + muon_labels + matrix_labels + local_labels
        ), "All params must have label"

        self.adam_opt = DistAdam(
            adam_params,
            adam_labels,
            lr=0.004,
            betas=(0.8, 0.95),
            eps=1e-8,
            weight_decay=0.005,
        )
        self.scalar_opt = DistAdam(
            scalar_params,
            scalar_labels,
            lr=0.008,
            betas=(0.9, 0.99),
            eps=1e-8,
            weight_decay=0.005,
        )
        self.muon_opt = NorMuon(
            muon_params, lr=0.015, momentum=0.95, beta2=0.95, weight_decay=1.2
        )
        self.optimizers = [self.adam_opt, self.scalar_opt, self.muon_opt]
        if local_params:
            world = dist.get_world_size()
            groups = [dist.new_group([r]) for r in range(world)]  # collective: every rank makes all
            self.local_opt = NorMuon(
                local_params, lr=0.015, momentum=0.95, beta2=0.95, weight_decay=1.2,
                group=groups[dist.get_rank()],
            )  # fmt: skip
            self.optimizers.append(self.local_opt)
        if matrix_params:
            self.matrix_opt = DistAdam(
                matrix_params,
                matrix_labels,
                lr=model.matrix_adam,
                betas=(0.9, 0.95),
                eps=1e-8,
                weight_decay=model.matrix_wd,
            )
            self.optimizers.append(self.matrix_opt)
        # split after odd number step
        self.split_step = (
            math.ceil(args.split_embed_frac * args.num_scheduled_iterations) | 1
        )

        # set defaults
        for opt in self.optimizers:
            opt.freeze_timer = 0
            opt.odd_step_only = False
            opt.should_sync = True
            for group in opt.param_groups:
                group["initial_lr"] = group["lr"]

        # on even steps, only step Muon params
        self.adam_opt.odd_step_only = True
        self.scalar_opt.odd_step_only = True

        self.reset()

    def _build_mtp_schedule(self):
        # Precompute MTP weights for all steps to avoid tensor allocation during training
        # Schedule: [1, 0.5, 0.25->0] -> [1, 0.5->0] -> [1]
        mtp_weights_schedule = []
        for s in range(args.num_iterations + 1):
            x = s / (args.num_scheduled_iterations / 4)
            if x < 1 / 3:
                w = [1.0, 0.5, 0.25 * (1 - 3 * x)]
            elif x < 2 / 3:
                w = [1.0, 0.5 * (1 - (3 * x - 1))]
            else:
                w = [1.0]
            mtp_weights_schedule.append(torch.tensor(w, device=device))
        return mtp_weights_schedule

    def apply_final_ws_ext(self):
        self.ws_long = args.ws_validate_post_yarn_ext

    def get_forward_args(self):
        return ForwardScheduleConfig(
            mtp_weights=self.mtp_weights, ws_short=self.ws_short, ws_long=self.ws_long
        )

    def _is_active_step(self, opt, step: int):
        return (opt.odd_step_only and step % 2 == 1) or not opt.odd_step_only

    def get_transition_steps(self):
        transition_steps = [0]
        ws_short, ws_long = get_ws(0)
        for step in range(1, args.num_iterations):
            ws_short, new_ws_long = get_ws(step)
            if new_ws_long != ws_long:
                transition_steps.append(step)
                ws_long = new_ws_long
        return transition_steps

    def advance_schedule(self, step: int):
        self.ws_short, new_ws_long = get_ws(step)
        # only apply yarn for first few
        if new_ws_long != self.ws_long and new_ws_long <= 13:
            self.model.yarn.apply(self.ws_long, new_ws_long)

        new_batch_size = get_bs(step)
        if new_batch_size != self.batch_size:
            self.train_loader_send_args = (
                new_batch_size,
                args.train_max_seq_len,
                grad_accum_steps,
            )
        else:
            self.train_loader_send_args = None

        self.ws_long = new_ws_long
        self.mtp_weights = self.mtp_weights_schedule[step]

    def step_optimizers(self, step: int):
        step_lr = get_lr(step)
        muon_momentum = get_muon_momentum(step)
        for opt in (self.muon_opt, getattr(self, "local_opt", None)):
            for group in opt.param_groups if opt else ():
                group["momentum"] = muon_momentum

        for opt in self.optimizers:
            if opt.freeze_timer > 0:
                opt.freeze_timer -= 1
                opt.zero_grad(set_to_none=True)
            else:
                if self._is_active_step(opt, step):
                    for group in opt.param_groups:
                        group["lr"] = group["initial_lr"] * step_lr
                    opt.step()
                    opt.zero_grad(set_to_none=True)
                    if isinstance(opt, DistAdam):  # re-armed on the last micro-batch
                        opt.should_sync = False

        # prop bias rule: full speed for the first 80% of training, then linearly to 0 at the end
        # (DeepSeek-V3 stops bias updates in its final phase)
        if self.moe:
            n = args.num_iterations
            scale = min(1.0, max(0.0, (n - step) / (0.2 * n)))
            for m in self.moe:
                m.rebalance(scale)

        if step == self.split_step:
            self.adam_opt.copy_lm_to_embed()
            self.model.split_embed = True

    def start_transition(self, freeze_count=40):
        # freeze scalar weights during transition
        self.scalar_opt.freeze_timer = freeze_count

    def activate_hooks(self, step: int):
        for opt in self.optimizers:
            if self._is_active_step(opt, step):
                opt.should_sync = True

    def reset(self, state=None):
        if state is not None:
            for opt, opt_state in zip(self.optimizers, state):
                opt.should_sync = False
                opt.load_state_dict(opt_state)

        # muon momentum buffers not in state dict
        self.muon_opt.reset()
        if hasattr(self, "local_opt"):
            self.local_opt.reset()
        self.model.split_embed = False

        self.ws_short, self.ws_long = get_ws(0)
        self.batch_size = get_bs(0)
        self.model.yarn.reset()

    def get_state(self):
        return [copy.deepcopy(opt.state_dict()) for opt in self.optimizers]


# -----------------------------------------------------------------------------
