"""Reproducible, narrow patch of the pinned MIT-licensed medium implementation.

Run this to regenerate modded_medium_core.py; edit the patch here, not that file.
The optimizer algorithms, kernel implementations and training schedules remain
upstream code. The chess adapter supplies attention, targets, data and recovery.
"""
import difflib
import hashlib
import json
from pathlib import Path

COMMIT = 'ecbb586296d3dac36fd206211f25d63bad4a6b35'
ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path('/data/group_data/dei-group/yimingz3/allie/upstream/modded-nanogpt') / COMMIT


def build():
    manifest = json.loads((SOURCE / 'SOURCE.json').read_text())
    original = (SOURCE / 'train_gpt_medium.py').read_text()
    assert hashlib.sha256(original.encode()).hexdigest() == manifest['files']['train_gpt_medium.py']
    source = original[:original.index('# int main')]

    def replace(old, new):
        nonlocal source
        assert source.count(old) == 1, old[:100]
        source = source.replace(old, new)

    replace('with open(sys.argv[0]) as f:\n    code = f.read()  # read the code of this file ASAP, for logging\n', '')
    replace('torch.empty(\n    1, device=f"cuda:{os.environ[\'LOCAL_RANK\']}", requires_grad=True\n).backward()  # prevents a bug on some systems\n', '')
    replace('from kernels import get_kernel\n', '')
    replace("flash_attn_interface = get_kernel('varunneal/flash-attention-3').flash_attn_interface", '# Attention backend is supplied by modded_medium.py.')
    replace('''        y = flash_attn_interface.flash_attn_varlen_func(q[0], k[0], v[0], cu_seqlens_q=seqlens, cu_seqlens_k=seqlens,
                                                        max_seqlen_q=max_len, max_seqlen_k=max_len,
                                                        causal=True, softmax_scale=attn_scale, window_size=(bm_size, 0))''',
            '        y = medium_attention(q, k, v, seqlens, bm_size, attn_scale)')
    replace('''            k[:, 1:, :, self.head_dim // 4:self.head_dim // 2] = k[:, :-1, :, self.head_dim // 4:self.head_dim // 2]
            k[:, 1:, :, 3 * self.head_dim // 4:] = k[:, :-1, :, 3 * self.head_dim // 4:]''',
            '''            same = seqlens.same_previous[1:][None, :, None, None]
            # Keep a game's first key intact; never import the preceding game.
            k = k.clone()
            k[:, 1:, :, self.head_dim // 4:self.head_dim // 2] = torch.where(same,
                k[:, :-1, :, self.head_dim // 4:self.head_dim // 2].clone(),
                k[:, 1:, :, self.head_dim // 4:self.head_dim // 2])
            k[:, 1:, :, 3 * self.head_dim // 4:] = torch.where(same,
                k[:, :-1, :, 3 * self.head_dim // 4:].clone(), k[:, 1:, :, 3 * self.head_dim // 4:])''')
    replace('x = torch.cat([x[:1], x[1:] + smear_gate_out * x[:-1]])',
            'x = torch.cat([x[:1], x[1:] + smear_gate_out * x[:-1] * seqlens.same_previous[1:, None]])')
    # Leave the upstream feature computation untouched. Chess loss and eval
    # share one explicit output support in the adapter, including auxiliary CE.
    start = source.index('        if not self.training:\n            loss = 0', source.index('class GPT('))
    end = source.index('\n# -----------------------------------------------------------------------------\n# Distributed data loader', start)
    source = source[:start] + '''        logits = self.lm_head(x)
        return 23 * torch.sigmoid((logits + 5) / 7.5)
''' + source[end:]
    # Unused FineWeb loader functions are omitted, not replaced with a new
    # optimizer/training implementation. Keep get_bs/get_ws and manager intact.
    start = source.index('def _load_data_shard(')
    end = source.index('def get_bs(', start)
    source = source[:start] + source[end:]
    header = f'''# Derived from KellerJordan/modded-nanogpt {COMMIT}.
# MIT license: modded_medium_LICENSE. Generated by build_modded_medium.py.
# Exact upstream and patch manifest are retained durably; do not hand-edit.
'''
    target = ROOT / 'scripts/modded_medium_core.py'
    target.write_text(header + source)
    (target.parent / 'modded_medium_LICENSE').write_bytes((SOURCE / 'LICENSE').read_bytes())
    patch = ''.join(difflib.unified_diff(original.splitlines(True), source.splitlines(True),
        fromfile='upstream/train_gpt_medium.py', tofile='allie/modded_medium_core.py'))
    (ROOT / 'results/modded-medium-port.patch').write_text(patch)
    (ROOT / 'results/modded-medium-port-source.json').write_text(json.dumps(dict(
        commit=COMMIT, upstream_sha256=manifest['files']['train_gpt_medium.py'],
        generated_sha256=hashlib.sha256(target.read_bytes()).hexdigest(),
        patch_sha256=hashlib.sha256(patch.encode()).hexdigest()), indent=2) + '\n')
    print(target)


if __name__ == '__main__':
    build()
